version: '3'
services:
  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  client:
      build: ./client
      ports:
          -  80:80
          -  443:443

volumes:
  redis_data:
