version: '3'
services:
    server:
        build: ./server
        ports:
          - 5000:5000
        env_file:
            - ./server/.env
        depends_on:
            - redis
    redis:
      image: redis
      ports:
          - 6379:6379
      volumes:
        - redis_data:/data


volumes:
    redis_data:
