TYPE_NOTIFICATION_ACTION_PROJECT = "action_project"
TYPE_NOTIFICATION_ADD_INTO_PROJECT = "add_into_project"
TYPE_NOTIFICATION_DELETE_PROJECT = "delete_project"
TYPE_NOTIFICATION_EDIT_PROJECT = "edit_project"
